name: individualprojectfinal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.7.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  pumli: ^0.1.5
  code_uml: ^0.0.1


dev_dependencies:
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  test: any


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


